config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#index'

      resources :books
      resources :users do
        resources :articles do
          resources  :comments
        end
      end

      resources :articles do
        member do
          post 'like' 
          post 'dislike' 
        end
      end

end

app/models/annu.rb
class Annu < ActiveRecord::Base
	validates :name, presence: true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	#has_many :likes, dependent: :destroy 
	acts_as_votable
	validates :title, presence: true

	def up_total
    self.likes.where(like: true).size
  end

  def down_total
    self.likes.where(like: false).size
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :article
	validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?
  	protected
	    def configure_permitted_parameters
	  		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation) }
	    end

 			def after_sign_up_path_for(resource)
	      user_articles_path(resource.id)
	    end

	    def after_sign_in_path_for(resource)
	      user_articles_path(resource.id)
	    end

	    def after_sign_out_path_for(resource_or_scope)
	    	'/users/sign_in'
	    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :user_id
	before_action :authenticate_user!, only: [:create]

	def new
		@article = Article.new
	end

	def create
		@article = @user.articles.create(article_params)
		if @article.save
			redirect_to user_articles_path
		else
			render 'new'
		end	
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to user_articles_path
		end
	end

	def index
		@articles = Article.all.includes(:comments)
	end

	def destroy
		@article = Article.find(params[:id])
		if @article.destroy
			redirect_to user_articles_path
		end
	end

	def like
    @article = Article.find(params[:id])
    #@article.like.create
    redirect_to user_articles_path
	end

	def dislike
    @article = Article.find(params[:id])
    #@article.dislike_from current_user
    redirect_to user_articles_path
	end


	private
  def user_id
    @user = User.find_by(id: params[:user_id])
  end

  def article_params
	  params.require(:article).permit(:title, :user_id)
  end

  def get_vote
  current_article = @article.detect{|r| r.id == params[:id].to_i}
  @article = current_article.likes.find_by_user_id(current_user.id)
  unless @like
    @like = Like.create(:user_id => current_user.id, :value => 0)
    current_article.likes << @like
  end
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
		@annu = Annu.new
	end

	def create
		@annu = Annu.create(annu_params)
		if @annu.save
			redirect_to books_path
		else
			render 'new'	
		end
	end

  def edit
  	@annu = Annu.find(params[:id])
	end

	def show
		@annu = Annu.find(params[:id])
	end

	def index
		@annus = Annu.all
	end

	def destroy
		@annu = Annu.find(params[:id])
		if @annu.destroy
			redirect_to books_path
		end	
	end

	def update
		@annu = Annu.find(params[:id])
		if @annu.update(annu_params)
			redirect_to books_path
		else
			render 'edit'
		end
	end

	private

	def annu_params 
		params.require(:annu).permit(:name)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :user_id
	before_action :authenticate_user!, only: [:create] 

	def new
		@article = Article.find(params[:article_id])
		@comment = Comment.new
	end

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		@comment.user_id = current_user.id
			if @comment.save
				redirect_to user_articles_path 
	 		else
	 			render 'new'
	 		end      
	end

	def index
		@article = Article.find(params[:article_id])
		@comments = Comment.all
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		if @comment.destroy
			redirect_to user_articles_path
		end
	end

	private
	def user_id
		@user = User.find_by(id: params[:user_id])
	end

	def comment_params
		params.require(:comment).permit(:text, :article_id, :user_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = current_user
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for ([@user, @user.articles.build]) do |f| %>
	<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %>
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.label :article_name %><br>
	<%= f.text_area :title, :rows => 5, :cols=>20 %>
	<%= f.submit 'write' %>
<% end %>

app/views/articles/edit.html.erb
<%= form_for :article, url: user_article_path(@user.id,@article.id), method: :patch do |f| %>
	<%= f.label :article_name %><br>
	<%= f.text_area :title, :rows => 5, :cols=>20 %>
	<%= f.submit 'Submit' %>
<% end %>

app/views/articles/index.html.erb
<%= link_to 'new post', new_user_article_path(@user.id) if user_signed_in?  %><br><br>
	<% if @articles.present? %>
		<% @articles.each do |article| %>
			Article:
			<%= article.title %> &nbsp; &nbsp;
			<%= article.user.email %>
		<% 	if user_signed_in? %>
			<%= link_to 'delete', user_article_path(@user.id,article.id), method: :delete if current_user.id == article.user.id %>
			<%= link_to "show", user_article_path(@user.id,article.id) if  current_user.id == article.user.id %>
			<%= link_to "edit",  edit_user_article_path(@user.id,article.id) if  current_user.id == article.user.id %><br>
	  <% end %>
	<br>
			<% article.comments.each do |comment| %>
				<%= comment.text %> &nbsp; &nbsp;
				<%= comment.user.email %><br>
				<% if user_signed_in? %>
					<% if comment.id != nil %>
						<%= link_to "Delete", user_article_comment_path(comment.user.id,comment.article.id,comment.id), method: :delete, data: { confirm: 'Are you sure?' } if current_user.id == comment.user.id %><br>
					<% end %>
				<% end %>
			<% end %>	
		<% if user_signed_in? %>
			<%= render partial: '/comments/form', :locals => {:@article => article} %><br>
		<% else %>
			<%= render partial: '/comments/index', :locals => {:@article => article} %><br>
		<% end %>
		<% end %>
	<% end 	%>

app/views/articles/new.html.erb
<div id ="articles">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<%= @article.title%>

<%= link_to "like", like_article_path(@article.id), method: :post %>
<%#= link_to "Dislike", dislike_articles_path(@artilce), method: :put %>

app/views/books/edit.html.erb
<%= form_for :annu, url: book_path(@annu), method: :patch  do |f| %>
	<%= f.label :book_name %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/books/index.html.erb
<%= link_to 'new', new_book_path %>
<br>
<% if @annus.present? %>
	<% @annus.each do |annu| %>
	<%= annu.name %>
	<%= link_to 'edit', edit_book_path(annu) %>
	<%= link_to 'delete', book_path(annu), method: :delete %>
	<%= link_to 'show', book_path(annu) %><br>
	<% end %>
<% end %>

app/views/books/new.html.erb
<%= form_for (@annu), url: books_path, method: :post do |f| %>
<%#= form_for (@annu), url: books_path do |f| %>
<%#= form_for (@annu), :url => {:action => "create"}, :method => "post" do |f| %>
	<% if @annu.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@annu.errors.count, "error") %> prohibited
        this annu from being saved:
      </h2>
      <ul>
        <% @annu.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
	 <% end %>
	<p>
		<%= f.label :book_name %>	
		<%= f.text_field :name %>
		<%= f.submit %>
	</p>
<% end %>	

app/views/books/show.html.erb
<%= @annu.name %>

app/views/comments/_form.html.erb
<%= form_for([@article,@article.comments.build], url: user_article_comments_path(@user.id,@article.id), method: :post) do |f| %>
    <%  if @comment && @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %>
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
	<%= hidden_field_tag :user_id, params[:user_id] %>
	<%= hidden_field_tag :article_id, params[:article_id] %>
	<%= f.label :Comment %>
	<%= f.text_field :text %>
	<%= f.submit %>
<% end %>

app/views/comments/_index.html.erb
<%= form_for([@article,@article.comments.build], url: '/users/:user_id/articles/:article_id/comments', method: :post) do |f| %>
	<%= hidden_field_tag :user_id, params[:user_id] %>
	<%= hidden_field_tag :article_id, params[:article_id] %>
	<%= f.label :Comment %>
	<%= f.text_field :text %>
	<%= f.submit 'comment' %>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= j (render :partial => 'comments/form')  %>");
//$('#comments').append("<%= j (render @comments) %>");
//$("#comments")[0].reset();
$("#comments")[0].reset();
 

app/views/comments/new.html.erb
<div id = "comments">
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apps</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
	<div class='log' >	 
  	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
	</div>  
<% end %>
<%= yield %>

</body>
</html>